#!/usr/bin/env bash

main() {
    case "$1" in
        pod02)
            rm ~/.datica
            ;;
        pod03)
            rm ~/.datica
            ;;
        pod05)
            rm ~/.datica
            export AUTH_HOST=https://auth.de.datica.com
            export PAAS_HOST=https://paas-api.de.datica.com
            export DATICA_ENV=8c38fcc0-132b-4580-bdac-673ad392b374
            ;;
        sbox05)
            rm ~/.datica
            export PAAS_HOST=https://sandbox-darwin.catalyzeapps.com
            export AUTH_HOST=https://auth-sandbox.catalyzeapps.com
            export ACCOUNTS_HOST=https://product-sandbox.catalyzeapps.com/stratum
            ;;
        *)
            cmds $0 main
            exit 1
            ;;
    esac
}

main "$@"
