#!/usr/bin/env bash

main() {
    ALIAS="$1" ; shift 1
    case "$ALIAS" in
        core)
            LOCAL_PORT=8090
            FORWARD_HOST=localhost
            FORWARD_PORT=8080
            REMOTE_HOST=172.27.24.113
            REMOTE_PORT=22
            ;;
        pod05)
            LOCAL_PORT=8090
            FORWARD_HOST=localhost
            FORWARD_PORT=8080
            REMOTE_HOST=sensu.pod05.catalyzeapps.com
            REMOTE_PORT=22
            ;;
        web)
            LOCAL_PORT=8090
            FORWARD_HOST=localhost
            FORWARD_PORT=8080
            REMOTE_HOST=172.26.28.82
            REMOTE_PORT=22
            ;;
        *)
            cmds $0 main
            exit 1
            ;;
    esac
    echo "http://localhost:${LOCAL_PORT} --> ${REMOTE_HOST}:${REMOTE_PORT} --> ${FORWARD_HOST}:${FORWARD_PORT}"
    ssh "$@" -N -L "${LOCAL_PORT}:${FORWARD_HOST}:${FORWARD_PORT}" "ssh://${REMOTE_HOST}:${REMOTE_PORT}"
}

main "$@"
