#!/usr/bin/env bash

main() {
    ALIAS="$1" ; shift 1
    case "$ALIAS" in
        core)
            LOCAL_HOST=localhost
            LOCAL_PORT=8090
            REMOTE_HOST=172.27.24.113
            REMOTE_PORT=8080
            ;;
        pod05)
            LOCAL_HOST=localhost
            LOCAL_PORT=8090
            REMOTE_HOST=sensu.pod05.catalyzeapps.com
            REMOTE_PORT=8080
            ;;
        web)
            LOCAL_HOST=localhost
            LOCAL_PORT=8090
            REMOTE_HOST=172.27.24.113
            REMOTE_PORT=8080
            ;;
        *)
            cmds $0 main
            exit 1
            ;;
    esac
    echo "http://${LOCAL_HOST}:${LOCAL_PORT} --> ${REMOTE_HOST}:${REMOTE_PORT}"
    ssh "$@" -N -L "$LOCAL_PORT":"$LOCAL_HOST":"$REMOTE_PORT" $REMOTE_HOST
}

main "$@"
