#!/bin/bash

# exit if error
set -e

cd "$HOME"
for config in $(ls -A "$HOME"/.environment/configs/.)
do
  ln -sf "$HOME"/.environment/configs/"$config"
done

touch "$HOME"/.bashrc
if ! grep -Fxq "if [ -f ~/.bash_aliases ]; then" "$HOME"/.bashrc
then
    printf "# User specific aliases and functions\nif [ -f ~/.bash_aliases ]; then\n\t. ~/.bash_aliases\nfi\n" >>"$HOME"/.bashrc
fi
