#!/usr/bin/env bash

main() {
    : "${STACKS:?This environment variable needs to be defined.}"
    stack="$(_doc_ls_ -C "$1")"
    [ "$stack" == "$1" ] && shift 1
    case $1 in
        ls)     shift 1 ; _doc_ls_ "$@" ;;
        stats)  shift 1 ; _doc_stats_ "$@" ;;
        *)      _docker-compose "$@" ;;
    esac
}

_doc_ls_() { 
    case "$1" in
        -a|--all)
            echo "$(
                for s in $(_doc_ls_) ; do
                    echo "$s"
                    sed -E 's/^/-- /' <<< "$(stack=$s ; _doc_ls_ -s)"
                done
            )"
            ;;
        -c|--configs)
            shift 1
            find -LE "$STACKS"/"$stack" -type f -regex ".*/docker-compose.*$1\$" | sort
            ;;
        -C|--check-stack)
            shift 1
            local check_stack="$(compgen -W "$(_doc_ls_)" -- "$1" | head -1)"
            if [ "$check_stack" == "$1" ] ; then
                echo "$check_stack"
                return 0
            fi
            local check_stack="$(compgen -W "$(_doc_ls_)" -- "$STACK" | head -1)"
            if [ "$check_stack" == "$STACK" ] ; then
                echo "$check_stack"
                return 0
            fi
            echo "$(_doc_ls_ | head -1)"
            ;;
        -s|--services)
            shift 1
            for config in $(_doc_ls_ -c "\.(yml|yaml)") ; do
                sed -En 'N ; s/^services:\n *(.*):/\1/ ; t end ; D ; :end p ; q' "$config"
            done | sort
            ;;
        *|-S|--stacks)
            find -E "$STACKS" -mindepth 1 -maxdepth 1 -type d -regex ".*/[^/.]*" -exec basename {} \; | sort
            ;;
    esac
}

_doc_stats_() {
    docker stats $(docker ps --format "{{.Names}}")
}

_docker-compose() {
    local arg args cmd srvcs
    cmd=$1 ; shift 1
    while [ -n "$1" ] ; do
        case "$1" in
            --) 
                shift 1
                srvcs+=( "$@" )
                args+=( "$@" )
                shift "$#" 
                ;;
            -*) 
                args+=( "$1" )
                shift 1
                ;;
            *)
                arg=$(compgen -W "$(_doc_ls_ -s)" -- "$1" | head -1)
                if [ "$arg" == "$1" ] ; then
                    srvcs+=( "$arg" )
                    args+=( "$arg" )
                else
                    args+=( "$1" )
                fi
                shift 1
                ;;
        esac
    done
    (
        # convert list to regex group
        _or_list() { sed 'y/ /|/ ; s/^/(/ ; s/$/)/' <<< "$*" ; }

        # set environment variables
        for f in $(_doc_ls_ -c "\.(var|vars)") ; do source "$f" ; done

        # run pre execution scripts
        for f in $(_doc_ls_ -c "$(_or_list "${srvcs[*]}")\.$cmd\.pre") ; do bash "$f" ; done

        # execute
        printf -v cmd_str -- "docker-compose%s --project-name $stack $cmd ${args[*]}\n" "$(printf -- " --file %s" $(_doc_ls_ -c "\.(yml|yaml)"))"
        eval "$cmd_str"

        # run post execution scripts
        for f in $(_doc_ls_ -c "$(_or_list "${srvcs[*]}")\.$cmd\.post") ; do bash "$f" ; done
    )
}

main "$@"
