#!/usr/bin/env bash

main() {
    case "$1" in
        exec)   shift 1 ; _doc_exec_ "$@" ;;
        oom)    shift 1 ; _doc_oom_ "$@" ;;
        stats)  shift 1 ; _doc_stats_ "$@" ;;
        *)      _docker_ "$@" ;;
    esac
}

_doc_exec_() {
    local JID="${1:?Job ID Required}" ; JID="${JID#_}" ; shift 1 ;
    screen -t "$JID" sudo -E docker exec -it "$@" "$JID" bash -c 'env \
        TERM=xterm-256color \
        EDITOR=$(which vim || which vi) \
        VISUAL=$(which vim || which vi) \
        PSQL_EDITOR=$(which vim || which vi) \
        bash -l -o vi \
    '
}

_doc_stats_() {
    if [ -n "$*" ] ; then
        sudo -E docker stats "${@#_}"
    else
        sudo -E docker stats $(sudo -E docker ps --format "{{.Names}}")
    fi
}

_doc_oom_() {
    sudo -E dmesg -T | grep "$(sudo -E docker inspect --format '{{.Id}}' "${1#_}")"
}

_docker_() {
    sudo -E docker "$@"
}

main "$@"
