#!/usr/bin/env bash

main() {
    case "$1" in
        cat)        shift 1 ; _elastic_cat_         "$@" ;;
        cluster)    shift 1 ; _elastic_cluster_     "$@" ;;
        log)        shift 1 ; _elastic_log_         "$@" ;;
        *)          
            if [ -z "$1" ] ; then
                curl -X GET 'localhost:9200?pretty'
            else
                echo "unknown command: $1"
                exit 1
            fi
            ;;
    esac
}

_elastic_cat_() {
    curl -X GET "localhost:9200/_cat/${1?Options: indices}?v"
}

_elastic_cluster_() {
    curl -X GET "localhost:9200/_cluster/${1?Options: health, state, stats}?human&pretty"
}

_elastic_log_() {
    search_directory="${ES_LOG_DIR:-/data/log/elasticsearch}/*"
    if [ -z "$1" ] ; then
        sed -n 's@^\(\[[^]]*\]\)\(\[[^]]*\]\)\(\[[^]]*\]\) \(\[[^]]*\]\) \(.*\)@\3@p' $search_directory | sort | uniq -c | sort -n
    else
        grep "\[[^]]*$1[^]]*\] " $search_directory
    fi
}

main "$@"
