#!/usr/bin/env bash

main() {
    case "$1" in
        uptime) shift 1 ; uptime "$@" ;;
        *) cmds ; exit 1 ;;
    esac
}

uptime() {
    sudo -E salt -C "${1:-*}" cmd.run "uptime -s" --output=text | grep -v "Minion did not return." | sort -k2
}

main "$@"
