#!/usr/bin/env bash

DOCKER_CMD=( $(pbpaste) )
JOBID=${DOCKER_CMD[4]}

IFS='' read -r -d '' SCRIPT <<- EOF
( 
    cd ~/.bash_temporary
    echo $JOBID > jobs
    cat jobs | sort | uniq > containers.tmp
    mv jobs.tmp jobs
)

exec "\$SHELL" --login -c 'screen -U -DR -S ssh -t host -p 0 ; logout'
EOF

# copy dot files to server and attach directly to a screen session
if [ -d ~/.shh/home ] ; then
    ( cd ~/.shh/home ; tar czh . ) | ssh -t "$1" "(cd ~ ; tar xz --overwrite) ; $SCRIPT"
else
    ssh -t "$1" "exec \"\$SHELL\" --login -c 'screen -U -DR -S ssh -t host -p 0 ; logout'"
fi

