#!/usr/bin/env bash

DOCKER_CMD=( $(pbpaste) )
JOBID=${DOCKER_CMD[4]}

# touch the known_hosts file if it doesn't exist
[ ! -e ~/.ssh/known_hosts ] && touch ~/.ssh/known_hosts

# copy environment to remote
[ -d ~/.shh/home ] && ( cd ~/.shh/home ; tar czh . ) | ssh "$1" "(cd ~ ; tar xz --overwrite ; echo '$JOBID' >> ~/.bash_temporary/jobs)"

# attach directly to a screen session
ssh "$@"
